version: '3.4'

services:
  app:
    image: cryptorealtimeprice
    build:
      context: .
      dockerfile: Dockerfile
    ports:
         - "5235:8080"
    environment:
      ASPNETCORE_URLS: "http://+:8080"